language: ruby
script: rspec

rvm:
  - 1.9.3
  - 2.1.2
  - 2.3.0
  - jruby-19mode

  - ruby-head
  - jruby-head

env:
  global:
    - VERBOSE=true
    - TIMEOUT=1

branches:
  only:
    - master

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head